version: '3.4'

services:    
  db:
     container_name: rushtowin_db
     image: mysql:5.7
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: rushtowin
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuserpassword
     ports:
      - "3306:3306"
     volumes:
       - dbdata:/var/lib/mysql
       - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
     restart: always


  rushtowin.api:
    container_name: rushtowin_api
    depends_on:
      - db
    image: ${DOCKER_REGISTRY-}rushtowinapi
    build:
      context: .
      dockerfile: RushToWin.API/Dockerfile
    ports:
      - "8080:5000"     


volumes:
  dbdata:
